export const BEAUTY_PRESETS = [
  // ── FACE ──
  {
    id: 'smooth',
    label: 'Soft Skin',
    emoji: '✨',
    color: '#ffb3d1',
    desc: 'Natural smoothing',
    prompt: 'subtle skin smoothing, soft skin texture, natural-looking complexion, light retouching, preserve all facial features and structure exactly, no plastic look, keep pores slightly visible, photorealistic',
  },
  {
    id: 'blemish',
    label: 'Clear Skin',
    emoji: '🌸',
    color: '#ff85b3',
    desc: 'Remove blemishes',
    prompt: 'clear skin, remove blemishes, acne, dark spots and pimples naturally, even skin tone, natural skin texture preserved, realistic result, do not alter facial structure',
  },
  {
    id: 'sharpen',
    label: 'Sharp Details',
    emoji: '💎',
    color: '#a78bfa',
    desc: 'Enhanced definition',
    prompt: 'sharpen and define facial features, enhance jawline definition, clear sharp details on eyes nose and face contours, high clarity, realistic photo quality, do not change facial structure',
  },
  {
    id: 'eyes',
    label: 'Bright Eyes',
    emoji: '👁️',
    color: '#60a5fa',
    desc: 'Vivid & expressive',
    prompt: 'enhance eyes naturally, brighter and more vivid irises, subtle catchlights, reduce under-eye dark circles and shadows, whiten sclera slightly, realistic look, preserve natural eye shape',
  },
  {
    id: 'glow',
    label: 'Natural Glow',
    emoji: '🌟',
    color: '#fbbf24',
    desc: 'Soft radiance',
    prompt: 'natural radiant skin glow, soft dewy complexion, balanced warm golden lighting on face, healthy luminous look, photorealistic, preserve all facial features exactly',
  },
  {
    id: 'beauty',
    label: 'Full Retouch',
    emoji: '💄',
    color: '#f43f5e',
    desc: 'Complete beauty',
    prompt: 'professional natural beauty retouch: smooth skin, clear complexion, bright vivid eyes, subtle glow, enhanced definition, balanced lighting, remove blemishes — all subtle and realistic, preserve full facial identity and structure exactly',
  },
  // ── HAIR ──
  {
    id: 'hair_dark',
    label: 'Black Hair',
    emoji: '🖤',
    color: '#818cf8',
    desc: 'Deep natural black',
    prompt: 'change hair color to natural deep black, rich glossy dark hair, natural hair texture preserved, realistic result, do not alter any other facial feature or background',
  },
  {
    id: 'hair_brown',
    label: 'Brown Hair',
    emoji: '🤎',
    color: '#92400e',
    desc: 'Rich & warm',
    prompt: 'change hair color to rich natural warm brown, chestnut brown tones, glossy realistic hair, preserve hair texture and style, do not alter face or background',
  },
  {
    id: 'hair_blonde',
    label: 'Blonde Hair',
    emoji: '💛',
    color: '#f59e0b',
    desc: 'Golden & natural',
    prompt: 'change hair color to natural golden blonde, warm honey blonde tones, realistic glossy hair, preserve hair texture and style exactly, do not alter face or background',
  },
  {
    id: 'hair_red',
    label: 'Red Hair',
    emoji: '🔴',
    color: '#dc2626',
    desc: 'Vibrant auburn',
    prompt: 'change hair color to vibrant natural red auburn, rich copper red tones, glossy realistic hair texture preserved, do not alter face or background',
  },
  {
    id: 'hair_platinum',
    label: 'Platinum',
    emoji: '⚪',
    color: '#94a3b8',
    desc: 'Cool ash tones',
    prompt: 'change hair color to platinum blonde ash white, cool icy platinum tones, realistic glossy hair, preserve hair texture and style, do not alter face or background',
  },
  {
    id: 'hair_colorful',
    label: 'Rainbow',
    emoji: '🌈',
    color: '#8b5cf6',
    desc: 'Creative gradient',
    prompt: 'apply a creative rainbow gradient hair color with vibrant purple pink and blue ombre tones, fantasy hair coloring, glossy realistic texture, do not alter face or background',
  },
  // ── COLOR EFFECTS ──
  {
    id: 'fx_warm',
    label: 'Warm Tone',
    emoji: '🌅',
    color: '#f97316',
    desc: 'Golden hour',
    prompt: 'apply warm golden hour color grading to the entire photo, warm orange amber tones, sun-kissed skin, soft warm shadows, cinematic warm look, realistic and natural',
  },
  {
    id: 'fx_cool',
    label: 'Cool Tone',
    emoji: '🧊',
    color: '#38bdf8',
    desc: 'Elegant & cinematic',
    prompt: 'apply cool blue teal color grading to the entire photo, cool cinematic tones, desaturated background with cool shadows, editorial cool look, realistic and natural',
  },
  {
    id: 'fx_bw',
    label: 'Black & White',
    emoji: '🎞️',
    color: '#6b7280',
    desc: 'High contrast',
    prompt: 'convert photo to high contrast black and white, dramatic B&W film photography style, deep shadows, bright highlights, grain texture, cinematic monochrome, preserve all details',
  },
  {
    id: 'fx_vintage',
    label: 'Vintage',
    emoji: '📷',
    color: '#d97706',
    desc: '70s film look',
    prompt: 'apply vintage film photo effect, faded warm tones, light leak effect, slight grain, retro color palette, 1970s film photography look, natural and realistic',
  },
  {
    id: 'fx_neon',
    label: 'Neon Glow',
    emoji: '🔮',
    color: '#c026d3',
    desc: 'Cyberpunk vibes',
    prompt: 'apply neon cyberpunk color effect, vibrant neon purple pink and blue light reflections on skin and background, dark moody atmosphere, neon glow on facial features, dramatic and realistic',
  },
  {
    id: 'fx_hdr',
    label: 'HDR Vivid',
    emoji: '🌈',
    color: '#10b981',
    desc: 'Punchy colors',
    prompt: 'apply HDR vivid color enhancement, boost saturation and vibrancy, rich deep colors, enhanced contrast, punchy colors, ultra detailed, realistic professional photography look',
  },
];